// Generated by CoffeeScript 1.11.1
(function() {
  var countdown, courses, dish, eat, food, foods, i, j, k, l, len, len1, len2, menu, num, ref;

  eat = function(food) {
    console.log(food);
    return false;
  };

  menu = function(num, dish) {
    console.log(num, dish);
    return false;
  };

  ref = ['toast', 'cheese', 'wine'];
  for (j = 0, len = ref.length; j < len; j++) {
    food = ref[j];
    eat(food);
  }

  courses = ['greens', 'caviar', 'truffles', 'roast', 'cake'];

  for (i = k = 0, len1 = courses.length; k < len1; i = ++k) {
    dish = courses[i];
    menu(i + 1, dish);
  }

  foods = ['broccoli', 'spinach', 'chocolate'];

  for (l = 0, len2 = foods.length; l < len2; l++) {
    food = foods[l];
    if (food !== 'chocolate') {
      eat(food);
    }
  }

  countdown = (function() {
    var m, results;
    results = [];
    for (num = m = 10; m >= 1; num = --m) {
      results.push(num);
    }
    return results;
  })();

  console.log(countdown);

}).call(this);

//# sourceMappingURL=2.for_in.js.map
