// Generated by CoffeeScript 1.11.1
(function() {
  var lyrics, num;

  if (this.studyEconomics) {
    while (supply > demand) {
      buy();
    }
    while (supply > demand) {
      sell();
    }
  }

  num = 6;

  lyrics = (function() {
    var results;
    results = [];
    while (num -= 1) {
      results.push(num + " little monkeys,jumping on the bed. One fell out bumped his head.");
    }
    return results;
  })();

}).call(this);

//# sourceMappingURL=4.while.js.map
